import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import { cn } from "@/lib/utils"

import "./globals.css";
import PageContainer from "@/components/shared/PageContainer";
import { ThemeProvider } from "@/components/theme-provider";
import { NotificationProvider } from "@/context/notification.context";
import { Toaster } from "@/components/ui/sonner";
import NotificationWrapper from "@/components/shared/NotificationContainer";
import dbConnect from "@/lib/mongodb";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})
export const metadata: Metadata = {
  title: "Seer Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await dbConnect();
  return (
    <html lang="en">
      <body className={cn(
        "min-h-screen bg-background font-sans antialiased",
        fontSans.variable
      )}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NotificationProvider>
            <NotificationWrapper>
              <PageContainer>
                {children}
              </PageContainer>
            </NotificationWrapper>
            <Toaster richColors position="bottom-right" expand={true} />
          </NotificationProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
